---

- name: NEW RELIC INFRA | Configure licence key
  template:
    src: etc/newrelic-infra.yml.j2
    dest: /etc/newrelic-infra.yml
    owner: root
    group: root

- name: NEW RELIC INFRA | Manage Redhat environment
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: NEW RELIC INFRA | Manage Debian environment
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: NEW RELIC INFRA | Install package
  package:
    name: newrelic-infra
    state: present
