---

###
# NEW RELIC AGENT
###

# Ubuntu repository
newrelic_apt_url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
newrelic_apt_repository: "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt {{ ansible_distribution_release }} main"

# New Relic licence key
# CAUTION : Use vault to encrypt the licence key
newrelic_licence_key: ""
